// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzThUxouZ77bHTYhL9pN9gqDMNqN82iWc',
    appId: '1:389928969996:web:6a478cf4f84229dfc58b29',
    messagingSenderId: '389928969996',
    projectId: 'emotional-alchemy-3d014',
    authDomain: 'emotional-alchemy-3d014.firebaseapp.com',
    storageBucket: 'emotional-alchemy-3d014.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvBACjPVPNUCG8It3NJGPIOr4_JnHjG2s',
    appId: '1:389928969996:android:8550a0259753d978c58b29',
    messagingSenderId: '389928969996',
    projectId: 'emotional-alchemy-3d014',
    storageBucket: 'emotional-alchemy-3d014.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzJlacHE_x1dCNOT7MNIhUd-8g5GDtldQ',
    appId: '1:389928969996:ios:d61dad40fcf3c136c58b29',
    messagingSenderId: '389928969996',
    projectId: 'emotional-alchemy-3d014',
    storageBucket: 'emotional-alchemy-3d014.firebasestorage.app',
    iosBundleId: 'com.example.emotionalAlchemy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzJlacHE_x1dCNOT7MNIhUd-8g5GDtldQ',
    appId: '1:389928969996:ios:d61dad40fcf3c136c58b29',
    messagingSenderId: '389928969996',
    projectId: 'emotional-alchemy-3d014',
    storageBucket: 'emotional-alchemy-3d014.firebasestorage.app',
    iosBundleId: 'com.example.emotionalAlchemy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzThUxouZ77bHTYhL9pN9gqDMNqN82iWc',
    appId: '1:389928969996:web:6bf9fd758c73cf60c58b29',
    messagingSenderId: '389928969996',
    projectId: 'emotional-alchemy-3d014',
    authDomain: 'emotional-alchemy-3d014.firebaseapp.com',
    storageBucket: 'emotional-alchemy-3d014.firebasestorage.app',
  );
}
